version: '3.8'
services:

  app:
    build: ./
    ports:
      - 80:80
      # - 443:443
      # - 5173:5173
    working_dir: /
    image: kouro_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    # command: bash -c "php /var/www/html/artisan migrate:fresh --seed && php-fpm"

  db:
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: kouro
      MYSQL_ROOT_PASSWORD: kouro
      MYSQL_PASSWORD: kouro
      MYSQL_USER: kouro
    volumes:
      - ./database_local:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
      PMA_USER: kouro
      PMA_PASSWORD: kouro
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
